### ISSUE TITLE
Trouble with generating grammar. Works from API. 

### ISSUE THREAD

**Issue by reverendpaco** [neogeny/TatSu#162] opened 2020-03-16 15:29 UTC
Running Tatsu 5.5.0 on Python 3.8.2.

The below grammar runs fine from an API perspective, and gives me what I want:

```
@@grammar::dql

start_goal
    =
    @:goal end_marker $
    ;

goal
    =   
     ( binary_relational_op )<{ named_predicate }+ ~
    | ( binary_relational_op )<{ goal }+ 
    | named_predicate:named_predicate 
    | grouped_relation:grouped_relation
    ;

grouped_relation
    =
    "(" @:goal ")"
    ;

named_predicate
    =
    functor:functor "(" args:args ")"
    ;

args 
    =
    | double_glob
    | glob
    ;

functor
    = 
    /[A-Za-z_]+[A-Za-z0-9_]*/
    ;

end_marker = '.';
binary_relational_op 
    =
    | right_outer_join
    | full_outer_join
    | left_outer_join
    | not_exists 
    | exists
    | intersect 
    | join 
    | union_all
    | union 
    | excessive_union 
    | flip_except_minus 
    | except_minus 
    ;

glob              = "*";
double_glob       = "**";
join              = ",";
left_outer_join   = "\," !"/";
right_outer_join  = ",/";
full_outer_join   = "\,/";
exists            = ",+";
not_exists        = ",\+";
union             = "\;";
union_all         = "\;/" ;
excessive_union   = ";";
intersect         = "^";
except_minus      = "-";
flip_except_minus = "-~";
```
Result from running from the API 
```javascript
# JSON
[
    "\\;/",
    {
        "grouped_relation": [
            "\\,",
            [
                ",",
                {
                    "functor": "daniel",
                    "args": "**"
                },
                {
                    "functor": "jane",
                    "args": "*"
                }
            ],
            {
                "functor": "john",
                "args": "*"
            }
        ]
    },
    {
        "functor": "bob",
        "args": "*"
    }
]
```

The API calling code:
```python
import json
from codecs import open
from pprint import pprint

import tatsu


def parse_example(parser,text):
    ast = parser.parse(text)

    print('# SIMPLE PARSE')
    print('# AST')
    pprint(ast, width=20, indent=4)

    print()

    print('# JSON')
    print(json.dumps(ast, indent=4))

def simple_parse():
    grammar = open('dql.ebnf').read()

    parser = tatsu.compile(grammar)
    t = r'''
    ( daniel (**),jane(*)\,john(*) )\;/bob(*)  .
    '''
    parse_example(parser,t)


def main():
    simple_parse()


if __name__ == '__main__':
    main()
```

Trying to generate the parser gives me the following error:
``` 
  File "/Users/doeklund/personal/logiteql/d2/lib/python3.8/site-packages/tatsu/codegen/python.py", line 134, in render_fields
    firstset = ' '.join(f[0] for f in sorted(self.node.lookahead()) if f)
TypeError: '<' not supported between instances of 'Group' and '_ref'
```
Command used:
```
python -m tatsu --name dql --generate-parser -o test.py dql.ebnf 
```

I took a look at the line in question and saw that the Group object had no comparator or string representation.  By removing the sorted() line 134 in codegen/python.py to
```python
         firstset = ' '.join(f[0] for f in self.node.lookahead()  if f)                                                                   
```

I got a different error:
```
  File "/Users/doeklund/personal/logiteql/d2/lib/python3.8/site-packages/tatsu/codegen/python.py", line 134, in render_fields
    firstset = ' '.join(f[0] for f in self.node.lookahead()  if f)
TypeError: sequence item 1: expected str instance, Group found
```

By adding repr() around the result I was finally able to get the parser generator to not error out.
```python
         firstset = ' '.join(repr(f[0]) for f in self.node.lookahead()  if f)                                                             
```

I know that what I was doing was just experimentation and that I am not qualified to guess what the error is, but I wanted to report to you my findings.

Finally, on trying to use this 'hacked' version of mine, the parser gave the following results:

```
python test.py < i.txt 
AST:
{'grouped_relation': None, 'named_predicate': None, 'parseinfo': [None, 'goal', 4, 45, 0, 0]}

JSON:
{
  "grouped_relation": null,
  "named_predicate": null,
  "parseinfo": [
    null,
    "goal",
    4,
    45,
    0,
    0
  ]
}
```

which seems close to issue:
https://github.com/neogeny/TatSu/issues/160#issue-561431213

Tatsu is great.  Thank you for all your hard work.

**Comment by tonico** [comment] 2020-07-04 11:48
I came across this error when I wanted to recompile my grammar with the current version of TatSu. The error can be reproduced with the following grammar `test.ebnf`:
```
a = ','.{ 'b' }+ | 'c' ;
```

```bash
$ tatsu test.ebnf
  ...
  "[...]/repo/TatSu/tatsu/codegen/python.py", line 134, in render_fields
    firstset = ' '.join(f[0] for f in sorted(self.node.lookahead()) if f)
TypeError: '<' not supported between instances of 'str' and 'Token'
```

This error occurs with Python 3.8.3 since commit bbe36b42647841530a9117e7b042415fbfc7c2e0.

When TaTsu is used as a library, it works as expected. The following Python script runs without errors.

```python
GRAMMAR = """
a = ','.{ 'b' }+ | 'c' ;
"""


def main():
    from tatsu import parse

    ast = parse(GRAMMAR, "b,b,b,b")
    print(ast)


if __name__ == "__main__":
    main()
```

**Comment by Victorious3** [comment] 2021-03-14 11:57
Probably related to #177

**Comment by Victorious3** [comment] 2021-03-16 18:55
Closing, feel free to open again if the issue persists. I tested @tonico's grammar and it worked fine with my changes.

**Closed by Victorious3** 2021-03-16 18:55 UTC
